version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8000"
    volumes:
    - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

